package com.minews1;

import android.Manifest;import android.app.Activity;import android.bluetooth.BluetoothAdapter;import android.bluetooth.BluetoothManager;import android.bluetooth.le.BluetoothLeScanner;import android.bluetooth.le.ScanCallback;import android.bluetooth.le.ScanResult;import android.bluetooth.le.ScanSettings;import android.content.Context;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.Build;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.os.ParcelUuid;import android.view.Gravity;import android.view.View;import android.view.Window;import android.view.WindowInsets;import android.widget.Button;import android.widget.LinearLayout;import android.widget.TextView;

public class MainActivity extends Activity{
 private static final String MAC="78:05:41:06:91:BA"; private static final ParcelUuid UUID=ParcelUuid.fromString("0000ffe1-0000-1000-8000-00805f9b34fb");
 private BluetoothLeScanner scanner; private ScanCallback callback; private final Handler main=new Handler(Looper.getMainLooper()); private HistoryDb db; private TextView temp,hum,status; private long lastSave=0; private float lastT=Float.NaN,lastH=Float.NaN;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new HistoryDb(this);showMain();if(needPermissions())requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},10);else startScan();}
 private boolean needPermissions(){return Build.VERSION.SDK_INT>=31 && (checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==10)startScan();}
 private TextView tv(String s,float size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setGravity(Gravity.CENTER);v.setPadding(10,10,10,10);return v;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 private void safeArea(LinearLayout root){
  if(Build.VERSION.SDK_INT>=35){
   root.setOnApplyWindowInsetsListener((v,insets)->{WindowInsets.Type t=WindowInsets.Type.systemBars();android.graphics.Insets i=insets.getInsets(t);v.setPadding(20,40+i.top,20,20+i.bottom);return insets;});
   root.requestApplyInsets();
  }
 }
 private void showMain(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER_HORIZONTAL);box.setPadding(20,40,20,20);safeArea(box);TextView title=tv("Minew S1",26);box.addView(title,new LinearLayout.LayoutParams(-1,70));temp=tv("— °C",64);hum=tv("— % RH",64);box.addView(temp,new LinearLayout.LayoutParams(-1,0,1));box.addView(hum,new LinearLayout.LayoutParams(-1,0,1));status=tv("Поиск датчика…",18);box.addView(status,new LinearLayout.LayoutParams(-1,70));Button history=btn("История");history.setOnClickListener(v->showHistory(24));box.addView(history,new LinearLayout.LayoutParams(-1,70));setContentView(box);}
 private void showHistory(long hours){stopScan();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(10,20,10,10);if(Build.VERSION.SDK_INT>=35){box.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(10,20+i.top,10,10+i.bottom);return insets;});box.requestApplyInsets();}LinearLayout bar=new LinearLayout(this);Button back=btn("←");back.setOnClickListener(v->{showMain();startScan();});bar.addView(back,new LinearLayout.LayoutParams(70,65));String[] labels={"1 ч","6 ч","24 ч","7 дней"};long[] vals={1,6,24,168};for(int i=0;i<labels.length;i++){final long x=vals[i];Button q=btn(labels[i]);q.setOnClickListener(v->loadGraph(x));bar.addView(q,new LinearLayout.LayoutParams(0,65,1));}box.addView(bar);GraphView graph=new GraphView(this);box.addView(graph,new LinearLayout.LayoutParams(-1,0,1));setContentView(box);loadGraph(hours);}
 private void loadGraph(long hours){View v=((android.view.ViewGroup)findViewById(android.R.id.content)).getChildAt(0);if(v instanceof android.view.ViewGroup){android.view.ViewGroup root=(android.view.ViewGroup)v;for(int i=0;i<root.getChildCount();i++)if(root.getChildAt(i) instanceof GraphView){((GraphView)root.getChildAt(i)).setData(db.since(System.currentTimeMillis()-hours*3600000L));break;}}}
 private void startScan(){if(needPermissions())return;BluetoothManager bm=(BluetoothManager)getSystemService(Context.BLUETOOTH_SERVICE);BluetoothAdapter a=bm.getAdapter();if(a==null||!a.isEnabled()){statusSafe("Включите Bluetooth");return;}scanner=a.getBluetoothLeScanner();if(scanner==null)return;callback=new ScanCallback(){@Override public void onScanResult(int type,ScanResult res){parse(res);}};scanner.startScan(null,new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).setReportDelay(0).build(),callback);}
 private void stopScan(){if(scanner!=null&&callback!=null){try{scanner.stopScan(callback);}catch(SecurityException ignored){}callback=null;}}
 private void parse(ScanResult res){if(res.getScanRecord()==null)return;byte[] d=res.getScanRecord().getServiceData(UUID);if(d==null||d.length<13|| (d[0]&255)!=0xA1 || (d[1]&255)!=0x01)return;int tr=(short)(((d[3]&255)<<8)|(d[4]&255));int hr=(short)(((d[5]&255)<<8)|(d[6]&255));float t=tr/256f,h=hr/256f;String embedded=String.format("%02X:%02X:%02X:%02X:%02X:%02X",d[12]&255,d[11]&255,d[10]&255,d[9]&255,d[8]&255,d[7]&255);String addr="";try{addr=res.getDevice().getAddress();}catch(SecurityException ignored){}if(!MAC.equalsIgnoreCase(addr)&&!MAC.equalsIgnoreCase(embedded))return;main.post(()->update(t,h));}
 private void update(float t,float h){temp.setText(String.format(java.util.Locale.US,"%.2f °C",t));hum.setText(String.format(java.util.Locale.US,"%.1f %% RH",h));status.setText("Датчик 78:05:41:06:91:BA  •  BLE");long now=System.currentTimeMillis();if(now-lastSave>=10000||Float.isNaN(lastT)||Math.abs(t-lastT)>=0.05f||Math.abs(h-lastH)>=0.05f){db.add(now,t,h);lastSave=now;lastT=t;lastH=h;}}
 private void statusSafe(String s){if(status!=null)status.setText(s);}
 @Override protected void onPause(){super.onPause();stopScan();}
 @Override protected void onResume(){super.onResume();if(temp!=null&&getWindow().getDecorView().getRootView().findViewById(android.R.id.content)!=null)startScan();}
}
